### ISSUE TITLE
UI5 Inspector no longer working in SAPUI5 v1.38. Error control.getMetadata(...).getProperty(...).getDefaultValue is not a function

### ISSUE THREAD

**Issue by KronicalZ** [SAP/ui5-inspector#207]
In recent updates in SAPUI5 v1.38 is no longer possible to use UI5 Inspector. The error received in the console is the following : ToolsAPI.js:264 Uncaught TypeError: control.getMetadata(...).getProperty(...).getDefaultValue is not a function.

In toolsAPI.js at line 264, is where the issue is identified :
 result.properties[key].isDefault = control.getMetadata().getProperty(key).getDefaultValue() === control.getProperty(key);
